apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: playground
  name: playground
spec:
  selector:
    matchLabels:
      app: playground
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - image: wil42/playground:v1
          name: playground
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
