apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: playground
  name: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: playground
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: playground
    spec:
      containers:
        - image: wil42/playground:v1
          name: playground
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always